// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVU6CEY5eAmhRrhOp11koHQCd00bxHwA',
    appId: '1:673530425307:web:ff3a534d3d6717ad2fc1fe',
    messagingSenderId: '673530425307',
    projectId: 'care-track-system-app',
    authDomain: 'care-track-system-app.firebaseapp.com',
    storageBucket: 'care-track-system-app.firebasestorage.app',
    measurementId: 'G-VWZEMFJ142',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgZlwIipDjcPnJqlehTX1MA4ZxF36JF8',
    appId: '1:673530425307:android:74b173b1c3b0cbde2fc1fe',
    messagingSenderId: '673530425307',
    projectId: 'care-track-system-app',
    storageBucket: 'care-track-system-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUUP9omafefFgKMhn3nvxpd3WJ5e46jU',
    appId: '1:673530425307:ios:83841206895a264a2fc1fe',
    messagingSenderId: '673530425307',
    projectId: 'care-track-system-app',
    storageBucket: 'care-track-system-app.firebasestorage.app',
    iosBundleId: 'com.example.childAndStudentCareAndTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGUUP9omafefFgKMhn3nvxpd3WJ5e46jU',
    appId: '1:673530425307:ios:83841206895a264a2fc1fe',
    messagingSenderId: '673530425307',
    projectId: 'care-track-system-app',
    storageBucket: 'care-track-system-app.firebasestorage.app',
    iosBundleId: 'com.example.childAndStudentCareAndTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGVU6CEY5eAmhRrhOp11koHQCd00bxHwA',
    appId: '1:673530425307:web:897deca08af8827b2fc1fe',
    messagingSenderId: '673530425307',
    projectId: 'care-track-system-app',
    authDomain: 'care-track-system-app.firebaseapp.com',
    storageBucket: 'care-track-system-app.firebasestorage.app',
    measurementId: 'G-0S67S4RBRX',
  );
}
